name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create build folder
      run: mkdir build && cd build

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-binutils

    - name: Install CMake
      uses: actions/setup-cmake@v3  # 这里使用官方 action，并指定合适的版本，v3 可根据实际情况调整

    - name: Configure CMake
      run: cmake.. -G "Visual Studio 17 2022"..

    - name: Build DLL
      run: msbuild Solstice.sln /p:Configuration=Release
      working-directory: build
