name: Windows 构建
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    - name: 安装 dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: 查找 msbuild.exe 路径
      run: |
        # 获取所有已安装的 SDK 信息
        $sdkInfo = & dotnet --list-sdks
        # 提取第一个 SDK 的安装路径
        $dotnetPath = $sdkInfo.Split("`n")[0].Trim().Split(' ')[0].Trim()
        # 去掉版本号部分，得到基础安装路径
        $dotnetPath = $dotnetPath.Substring(0, $dotnetPath.LastIndexOf('\\'))
        $msbuildPath = Join-Path -Path $dotnetPath -ChildPath'msbuild.exe'
        Write-Host "##vso[task.setvariable variable=MSBUILD_PATH]$msbuildPath"
      shell: powershell
    - name: 安装 Visual Studio 构建工具
      run: |
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive" -y
      shell: powershell
    - name: 创建构建文件夹
      run: |
        cd build
      shell: powershell
    - name: 安装 CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: 3.28
    - name: 配置 CMake
      run: cmake "D:\a\SnowClient\SnowClient" -G "Visual Studio 17 2022"
      shell: powershell
    - name: 使用 dotnet build 构建 DLL
      run: dotnet build "D:\a\SnowClient\SnowClient\Solstice.sln" -c Release
      working-directory: build
