name: Build Solstice DLL from CMakeLists.txt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-binutils

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release
      shell: bash

    - name: Build
      run: |
        # 尝试将构建命令拆分，避免可能的冲突
        cmake --build ${{github.workspace}}/build --config Release --target SolsticeShaders
        cmake --build ${{github.workspace}}/build --config Release --target generate_build_info
        cmake --build ${{github.workspace}}/build --config Release --target Solstice
      shell: bash

    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: Solstice.dll
        path: ${{github.workspace}}/build/Solstice.dll
