name: Build SnowClient DLL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: 3.28
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-openmp
    - name: Check find command availability
      shell: bash
      run: |
        if! command -v find &>/dev/null; then
          echo "find command not found. Please check the environment."
          exit 1
        fi
    - name: Locate WAVFileReader.cpp
      shell: bash
      run: |
        source_file=$(find. -name "WAVFileReader.cpp" | grep -i "directxtk-src/Audio")
        echo "SOURCE_FILE=$source_file" >> $GITHUB_ENV
    - name: Resolve function call ambiguity
      shell: cmd
      run: |
        set source_file=%SOURCE_FILE%
        set temp_file=%temp%\WAVFileReader_temp.cpp
        type nul > %temp_file%
        for /f "delims=" %%i in (%source_file%) do (
          set line=%%i
          setlocal enabledelayedexpansion
          set new_line=!line:safe_handle(=DirectX::safe_handle(!
          echo.!new_line!>> %temp_file%
          endlocal
        )
        move /y %temp_file% %source_file%
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release
    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: SnowClient DLL
        path: build/SnowClient.dll
