name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create build folder
      run: |
        mkdir build
        cd build
      shell: powershell

    - name: Copy CMakeLists.txt
      run: Copy-Item -Path../CMakeLists.txt -Destination.
      shell: powershell
      working-directory: build

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: 3.28

    - name: Configure CMake
      run: cmake .. -G "Visual Studio 17 2022" ..
      shell: powershell

    - name: Build DLL
      run: msbuild Solstice.sln /p:Configuration=Release
      working-directory: build
