name: Windows 构建
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    - name: 安装 dotnet
      uses: microsoft/setup-msbuild@v2
    - name: 输出当前工作目录
      run: Get-Location
      shell: powershell
    - name: 进入文件夹
      run: |
        cd build
      shell: powershell
    - name: 安装 CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
    - name: 配置 CMake
      run: cmake "D:\a\SnowClient\SnowClient" -G "Visual Studio 17 2022"
      shell: powershell
    - name: 解决函数调用冲突
      shell: cmd
      run: |
        set source_file=build\_deps\directxtk-src\Audio\WAVFileReader.cpp
        set temp_file=%temp%\WAVFileReader_temp.cpp
        type nul > %temp_file%
        for /f "delims=" %%i in (%source_file%) do (
          set line=%%i
          setlocal enabledelayedexpansion
          set new_line=!line:safe_handle(=DirectX::safe_handle(!
          echo.!new_line!>> %temp_file%
          endlocal
        )
        move /y %temp_file% %source_file%      
    - name: build
      run: msbuild "D:\a\SnowClient\SnowClient\Solstice.sln" /p:Configuration=Release
