name: Windows 构建
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    - name: 安装 dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: 添加.NET SDK 到环境变量
      run: |
        $dotnetPath = "${{ env.HOME }}/.dotnet/tools"
        if (-not (Test-Path $dotnetPath)) {
            New-Item -ItemType Directory -Force -Path $dotnetPath
        }
        [Environment]::SetEnvironmentVariable("PATH", "${{ env.HOME }}/.dotnet/tools;${{ env.PATH }}", [EnvironmentVariableTarget]::Process)
      shell: powershell
    - name: 进入文件夹
      run: |
        cd build
      shell: powershell
    - name: 安装 CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: 3.28
    - name: 配置 CMake
      run: cmake "D:\a\SnowClient\SnowClient" -G "Visual Studio 17 2022"
      shell: powershell
    - name: build
      run: msbuild "D:\a\SnowClient\SnowClient\Solstice.sln" /p:Configuration=Release
