name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: 3.28

    - name: Create build folder
      run: |
        mkdir build
        cd build
      shell: powershell

    - name: Verify CMakeLists.txt Existence
      run: |
        $parentDir = Join-Path -Path.. -ChildPath CMakeLists.txt
        if (-not (Test-Path $parentDir)) {
            Write-Error "CMakeLists.txt 在上一级目录中未找到。"
            exit 1
        }
      shell: powershell

    - name: Configure CMake
      run: cmake.. -G "Visual Studio 17 2022"
      shell: powershell

    - name: Build DLL
      run: msbuild Solstice.sln /p:Configuration=Release
      working-directory: build
