name: Windows 构建
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    - name: 安装 dotnet
      uses: microsoft/setup-msbuild@v2
    - name: 输出当前工作目录
      run: Get-Location
      shell: powershell
    - name: 进入文件夹
      run: |
        cd build
      shell: powershell
    - name: 安装 CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
    - name: 配置 CMake 并添加替换标志
      run: cmake "D:\a\SnowClient\SnowClient" -G "Visual Studio 17 2022" -DREPLACE_AMBIGUOUS_CALL=ON
      shell: powershell
    - name: 替换代码
      if: env.REPLACE_AMBIGUOUS_CALL == 'ON'
      run: |
        $file = "D:\a\SnowClient\SnowClient\_deps\directxtk-src\Audio\WAVFileReader.cpp"
        (Get-Content $file) | ForEach-Object {
          if ($_ -match 'DirectX::safe_handle\((.*?)\)') {
            # 这里假设 safe_handle 接收一个句柄类型参数，将其替换为带明确类型的调用
            $_ = $_ -replace 'DirectX::safe_handle\((.*?)\)', 'DirectX::safe_handle<HANDLE>(\1)'
          }
          $_
        } | Set-Content $file
      shell: powershell
    - name: build
      run: msbuild "D:\a\SnowClient\SnowClient\Solstice.sln" /p:Configuration=Release
