name: Build SnowClient DLL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      # 使用最新版本的 actions/checkout 动作获取代码
      uses: actions/checkout@latest
    - name: Setup MSBuild
      # 使用最新版本的 microsoft/setup-msbuild 动作设置 MSBuild 环境
      uses: microsoft/setup-msbuild@latest
    - name: Setup CMake
      # 使用最新版本的 jwlawson/actions-setup-cmake 动作设置 CMake 环境
      uses: jwlawson/actions-setup-cmake@latest
    - name: Install MSYS2
      uses: msys2/setup-msys2@latest
      with:
        update: true
        install: |
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-openmp
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release
    - name: Upload DLL
      uses: actions/upload-artifact@latest
      with:
        name: SnowClient DLL
        path: build/SnowClient.dll
