name: Windows Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # 根据需要调整.NET 版本
    - name: Check.NET Version
      run: |
        dotnet --version
      shell: powershell
    - name: Check MSBuild Existence
      run: |
        $msbuildPath = &dotnet --list-sdks | Select-String -Pattern "7.0" | ForEach-Object { $_.ToString().Split(' ')[0] }
        $msbuildPath = Join-Path -Path (Split-Path -Path $msbuildPath -Parent) -ChildPath "MSBuild\Current\Bin\msbuild.exe"
        if (-not (Test-Path -Path $msbuildPath)) {
            Write-Error "msbuild.exe not found"
            exit 1
        }
      shell: powershell
    - name: Add MSBuild Path
      run: |
        $msbuildPath = &dotnet --list-sdks | Select-String -Pattern "7.0" | ForEach-Object { $_.ToString().Split(' ')[0] }
        $msbuildPath = Join-Path -Path (Split-Path -Path $msbuildPath -Parent) -ChildPath "MSBuild\Current\Bin"
        $env:Path += ";$msbuildPath"
      shell: powershell
    - name: Create build folder
      run: |
        cd build
      shell: powershell
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: 3.28
    - name: Configure CMake
      run: cmake "D:\a\SnowClient\SnowClient" -G "Visual Studio 17 2022"
      shell: powershell
    - name: Check Solution File
      run: |
        $solutionFile = "Solstice.sln"
        if (-not (Test-Path -Path $solutionFile)) {
            Write-Error "Solution file $solutionFile not found"
            exit 1
        }
      shell: powershell
    - name: Build DLL
      run: msbuild Solstice.sln /p:Configuration=Release
      working-directory: build
