name: Build SnowClient DLL
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: 3.28
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-openmp
    - name: Resolve safe_handle ambiguity
      run: |
        $filePath = "D:/a/SnowClient/SnowClient/build/_deps/directxtk-src/Audio/WAVFileReader.cpp"
        $content = Get-Content -Path $filePath
        $newContent = $content -replace 'safe_handle\((.*?)\)', 'DirectX::safe_handle($1)'
        Set-Content -Path $filePath -Value $newContent
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release
    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: SnowClient DLL
        path: build/SnowClient.dll
