name: Build and Test Solstice

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MSYS2 and required packages
      uses: msys2/setup-msys2@v2
      with:
        update: true
      run: |
        msys2/setup-msys2@v2 -c "pacman --noconfirm -Syu"
        msys2/setup-msys2@v2 -c "pacman --noconfirm -S mingw-w64-x86_64-cmake mingw-w64-x86_64-toolchain mingw-w64-x86_64-binutils make"
      shell: bash

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      shell: bash

    - name: Build project
      run: |
        cmake --build ${{github.workspace}}/build --config Release
      shell: bash

    - name: Run tests (如果有测试的话)
      run: |
        # 这里假设项目有测试可执行文件，根据实际情况调整命令
        ${{github.workspace}}/build/your_test_executable
      shell: bash
