name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create build folder
      run: New-Item -ItemType Directory -Force -Path build

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-binutils

    - name: Setup CMake Environment
      uses: microsoft/setup-cmake@v1
      with:
        cmake-version: 3.28  # 根据实际需求修改 CMake 版本

    - name: Configure CMake
      shell: msys2 {0}
      run: |
        cd build
        cmake.. -G "Visual Studio 17 2022"..

    - name: Build DLL
      shell: cmd
      run: |
        cd build
        msbuild Solstice.sln /p:Configuration=Release
