name: Windows 构建2
on:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: windows-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
  install_dotnet:
    runs-on: windows-latest
    needs: checkout
    steps:
    - name: 安装 dotnet
      uses: microsoft/setup-msbuild@v2
  install_cmake:
    runs-on: windows-latest
    needs: checkout
    steps:
    - name: 安装 CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
  build_project:
    runs-on: windows-latest
    needs: [install_dotnet, install_cmake]
    steps:
    - name: 输出当前工作目录
      run: Get-Location
      shell: powershell
    - name: 进入文件夹
      run: |
        cd build
      shell: powershell
    - name: 配置 CMake
      run: cmake "D:\a\SnowClient\SnowClient" -G "Visual Studio 17 2022" -Wno-dev -j$(nproc)
      shell: powershell
    - name: build
      run: msbuild "D:\a\SnowClient\SnowClient\Solstice.sln" /p:Configuration=Release /m
      shell: powershell
