name: Windows 构建
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    - name: 安装 dotnet
      uses: microsoft/setup-msbuild@v2
    - name: 输出当前工作目录
      run: Get-Location
      shell: powershell
    - name: 进入文件夹
      run: |
        cd build
      shell: powershell
    - name: 安装 CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
    - name: 配置 CMake
      run: cmake "D:\a\SnowClient\SnowClient" -G "Visual Studio 17 2022"
      shell: powershell
    - name: 打包为 zip 压缩包
      uses: actions/upload-artifact@v3
      with:
        name: SnowClient.zip
        path: D:\a\SnowClient\SnowClient
